## Default Configuration File

# Server port number
serverPort: 8083
# Database file path
dbFile: proofs.db
# Number of worker threads
nWorkers: 2
# Proof lifetime in days
proofLifetime: 30
# Key lifetime in seconds
keysLifetime: 86400
# Delegation servers
delegationServers: []
